version: '3.8'
services:
  auth_service:
    build: ./
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/code/
    ports:
      - 8002:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    env_file:
      - .env
