version: '3.8'
services:
  api:
    build: .
    container_name: street-food-api
    ports:
      - 80:80
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    env_file:
      - .env
